const fs = require('fs');
let htmlFiles = fs.readdirSync('.').filter(f => f.endsWith('.html'));

// Update Account link in all HTML files
for(let file of htmlFiles) {
    let content = fs.readFileSync(file, 'utf8');
    // Using simple replace since the structure is consistent and generated by add-mobile-nav.js
    content = content.replace(/href="javascript:void\(0\)" class="mobile-nav-item">\s*<i class="ph ph-user"><\/i>\s*<span>Account<\/span>/g, 'href="login.html" class="mobile-nav-item">\n            <i class="ph ph-user"></i>\n            <span>Account</span>');
    fs.writeFileSync(file, content);
}

// Update js/main.js
let mainJs = fs.readFileSync('js/main.js', 'utf8');
mainJs = mainJs.replace(/<button class="menu-action-btn"><i class="ph ph-user"><\/i> Login<\/button>/g, '<button class="menu-action-btn" onclick="window.location.href=\'login.html\'"><i class="ph ph-user"></i> Login</button>');
fs.writeFileSync('js/main.js', mainJs);

// Update add-mobile-nav.js
if(fs.existsSync('add-mobile-nav.js')) {
    let addNavJs = fs.readFileSync('add-mobile-nav.js', 'utf8');
    addNavJs = addNavJs.replace(/href="javascript:void\(0\)" class="mobile-nav-item">\s*<i class="ph ph-user"><\/i>\s*<span>Account<\/span>/g, 'href="login.html" class="mobile-nav-item">\n            <i class="ph ph-user"></i>\n            <span>Account</span>');
    fs.writeFileSync('add-mobile-nav.js', addNavJs);
}

console.log("Replaced links successfully!");
